[default]
extend-ignore-re = [
	"(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
	"(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
	"(#|//)\\s*spellchecker:ignore-next-line\\n.*"
]
